name: Productize CI/CD Pipeline

on:
  push:
    branches: ["main"]

jobs:
  build:
    name: Build and Deploy
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Give checkout permission
        run: sudo chmod -R 777 /var/www/productize

      - name: 🚚 Get latest code
        uses: actions/checkout@v3

      - name: Setup Enviroment
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.1"
        env:
          runner: self-hosted

      - name: Copy env files from client config folder
        run: cp /var/www/config/.env /var/www/productize/_work/Productize-server/Productize-server/

      - name: Install Packages
        run: composer install --optimize-autoloader --no-dev

      - name: Autoload
        run: composer dump-autoload

      - name: Clear route
        run: php artisan route:clear

      - name: Clear Cache
        run: php artisan cache:clear

      - name: Clear Config
        run: php artisan config:clear

      - name: Generate storage link
        run: php artisan storage:link

      - name: Migrate Database
        run: php artisan migrate --force

      - name: Prune sanctum
        run: php artisan sanctum:prune-expired

      - name: Give permissions
        run:  |
         sudo chown -R www-data.www-data /var/www/productize/_work/Productize-server/Productize-server/storage
         sudo chown -R www-data.www-data /var/www/productize/_work/Productize-server/Productize-server/bootstrap/cache
         sudo chown -R www-data:www-data /var/www/productize/_work/Productize-server/Productize-server/storage/framework/views
