name: Development CI/CD Workflow

on:
  pull_request:
    branches: ["development"]
  push:
    branches: ["development"]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root_password
          MYSQL_DATABASE: productize_test
          MYSQL_USER: test
          MYSQL_PASSWORD: 123456
        ports:
          - 3306:3306
        options: >-
          --health-cmd "mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"

      - name: Install dependencies
        run: composer install --prefer-dist --no-interaction --no-scripts --no-progress --optimize-autoloader

      - name: Copy .env.example to .env
        run: cp .env.example .env

      - name: Generate APP_KEY
        run: php artisan key:generate

      - name: Create testing database
        run: |
          mysql -h 127.0.0.1 -u test -p123456 -e 'CREATE DATABASE IF NOT EXISTS productize_test;'

      - name: Run migrations
        run: php artisan migrate --env=testing

      - name: Run tests
        run: php artisan test

  build:
    if: ${{ github.event_name == 'push' }}
    name: Build and Deploy
    needs: test
    runs-on: [development]

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Give checkout permission
        run: sudo chmod -R 777 /var/www/dev

      - name: 🚚 Get latest code
        uses: actions/checkout@v3

      - name: Setup Environment
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
        env:
          runner: self-hosted

      - name: Copy env files from client config folder
        run: cp /var/www/config-dev/.env /var/www/dev/_work/Productize-server/Productize-server/

      - name: Install Packages
        run: composer install --optimize-autoloader --no-dev

      - name: Autoload
        run: composer dump-autoload

      - name: Clear caches
        run: php artisan optimize:clear

      - name: Generate new Cache
        run: php artisan optimize

      - name: Generate storage link
        run: php artisan storage:link

      # - name: Migrate Database
      #   run: php artisan migrate:fresh --force

      # - name: Database Seed
      #   run: php artisan db:seed

      # - name: Prune sanctum
      #   run: php artisan sanctum:prune-expired

      - name: Give permissions
        run: |
          sudo chown -R www-data.www-data /var/www/dev/_work/Productize-server/Productize-server/storage
          sudo chown -R www-data.www-data /var/www/dev/_work/Productize-server/Productize-server/bootstrap/cache
          sudo chmod -R 777 /var/www/dev/_work/Productize-server/Productize-server/storage
          sudo chmod -R 777 /var/www/dev/_work/Productize-server/Productize-server/bootstrap/cache

  lint:
    if: ${{ github.event_name == 'push' }}
    name: Fix Code Style
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        php: [8.3]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: json, dom, curl, libxml, mbstring
          coverage: none

      - name: Install Pint
        run: composer global require laravel/pint

      - name: Run Pint
        run: pint

      - name: Commit linted files
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Fixes coding style"
