name: Laravel Test

on: [pull_request]

jobs:
  laravel-tests-mysql:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root_password
          MYSQL_DATABASE: testing_database_name
          MYSQL_USER: your_username
          MYSQL_PASSWORD: your_password
        ports:
          - 3306:3306
        options: >-
          --health-cmd "mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Install dependencies
        run: composer install --prefer-dist --no-interaction --no-scripts --no-progress --optimize-autoloader

      - name: Copy .env.example to .env
        run: cp .env.example .env

      - name: Generate APP_KEY
        run: php artisan key:generate

      - name: Create testing database
        run: |
          mysql -h 127.0.0.1 -u test -p 123456 -e 'CREATE DATABASE IF NOT EXISTS productize_test;'

      - name: Run migrations
        run: php artisan migrate --env=testing

      - name: Run tests
        run: vendor/bin/phpunit
