name: Laravel

on:
  pull_request:
    branches: ["main"]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root_password
          MYSQL_DATABASE: productize_test
          MYSQL_USER: test
          MYSQL_PASSWORD: 123456
        ports:
          - 3306:3306
        options: >-
          --health-cmd "mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
        volumes:
          - ./.github/workflows/my.cnf:/etc/mysql/conf.d/my.cnf

    steps:
      - uses: actions/checkout@v3
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.1"
      - name: Copy .env.testing to .env
        run: php -r "file_exists('.env') || copy('.env.testing', '.env');"
      - name: Install Dependencies
        run: |
          composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
          echo $? # Output exit code
      - name: Generate key
        run: |
          php artisan key:generate
          echo $? # Output exit code
      - name: Directory Permissions
        run: |
          chmod -R 777 storage bootstrap/cache
          echo $? # Output exit code
      - name: Wait for MySQL to be ready
        run: |
          sleep 30
          while ! mysqladmin ping -h"127.0.0.1" --silent; do
            echo "Waiting for database connection..."
            sleep 5
          done
          echo $? # Output exit code
      - name: Prepare Database
        run: |
          php artisan migrate
          echo $? # Output exit code
        env:
          DB_CONNECTION: mysql
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_DATABASE: productize_test
          DB_USERNAME: test
          DB_PASSWORD: 123456
      - name: Execute tests (Unit and Feature tests) via PHPUnit
        run: |
          php artisan test
          echo $? # Output exit code
        env:
          DB_CONNECTION: mysql
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_DATABASE: productize_test
          DB_USERNAME: test
          DB_PASSWORD: 123456
