name: Laravel

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root_password
          MYSQL_DATABASE: productize_test
          MYSQL_USER: test
          MYSQL_PASSWORD: 123456
        ports:
          - 3306:3306
        options: >-
          --health-cmd "mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and run Docker containers
        run: |
          echo "version: '3.8'
          services:
            app:
              build: .
              container_name: app
              depends_on:
                - mysql
              volumes:
                - .:/var/www/html
              working_dir: /var/www/html
              environment:
                DB_CONNECTION: mysql
                DB_HOST: mysql
                DB_PORT: 3306
                DB_DATABASE: productize_test
                DB_USERNAME: test
                DB_PASSWORD: 123456
              command: >
                sh -c '
                  cp .env.testing .env &&
                  php artisan key:generate &&
                  chmod -R 777 storage bootstrap/cache &&
                  php artisan migrate &&
                  php artisan test
                '
            mysql:
              image: mysql:8.0
              env_file: .env.testing
              ports:
                - 3306:3306
              environment:
                MYSQL_ROOT_PASSWORD: root_password
                MYSQL_DATABASE: productize_test
                MYSQL_USER: test
                MYSQL_PASSWORD: 123456
              healthcheck:
                test: "mysqladmin ping --silent"
                interval: 10s
                timeout: 5s
                retries: 5
          " > docker-compose.yml

          docker-compose up --exit-code-from app
